name: CI/CD for .NET Application

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'  # Adjust the version as needed

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-app
        path: ./bin/Release/net6.0/publish  # Adjust the path as needed

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Deploy to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version --application-name your-application-name --version-label $GITHUB_SHA --source-bundle S3Bucket=$EB_BUCKET,S3Key=dotnet-app.zip
        aws elasticbeanstalk update-environment --environment-name your-environment-name --version-label $GITHUB_SHA

    - name: Clean up
      run: rm -rf ./bin ./obj  # Clean up artifacts and build files

